before_script:
    - apt update
    - apt install -y dh-virtualenv dpkg-dev dh-exec build-essential fakeroot git

include: 
    project: docker/template
    file: debian-pkg.yaml

##############################################################

build-newstable:nano:
    extends: .build_for_newstable
    tags: ['arm64']

build-newstable:rpi:
    extends: .build_for_newstable
    tags: ['armhf']

build-stable:nano:
    extends: .build_for_stable
    tags: ['arm64']

build-stable:rpi:
    extends: .build_for_stable
    tags: ['armhf']

build-oldstable:nano:
    extends: .build_for_oldstable
    tags: ['arm64']

build-oldstable:rpi:
    extends: .build_for_oldstable
    tags: ['armhf']

deploy-test:
    extends: .deploy_test

deploy-release:
    extends: .deploy_master
