# use the prepared docker image
# any dependencies - packages, etc - should be added to the definition
# of the builder image for speeding up the pipeline
image: $CI_REGISTRY/docker/bob-the-builder:latest

# even when the image will be prepared, it is good to put the build
# dependencies here for documentation purposes and making the dependencies
# more up to date, since the packages can receive updates from the moment
# when the builder image has been generated
before_script:
        - apt update
        - apt install -y dh-virtualenv dpkg-dev dh-exec build-essential fakeroot git

# there is only one pipeline stage and the result will be Debian packages build
# for two architectures: armhf and arm64

# builds package upon each commit to the test branch
# the version is taken from the commit date and time in format YYMMDDHHMMSS
build_from_test_on_rpi:
        only:
                - test
        tags:
                - armhf
        script:
                # one-liner for generating Debian changelog from last 10 commit messages
                - git log -10 --date="format:%Y%m%d%H%M%S" --pretty="evok (%ad) unstable; urgency=medium%n%n  * %s%n%n -- %an <%ae>  %aD %n" > debian/changelog 
                - dpkg-buildpackage -us -uc
                - mkdir build
                # the packages generated by the dpkg-buildpackage are save in the upper directory
                # we need to move them to the working copy of the repository to be able to pass them to Gitlab as artifacts
                - mv ../evok_`git log -1  --date="format:%Y%m%d%H%M%S" --pretty="%ad"`* build/
        artifacts:
                paths:
                        - build/*
                        - debian/changelog

build_from_test_on_nanopi:
        only:
                - test
        tags:
                - arm64
        script:
                # one-liner for generating Debian changelog from last 10 commit messages
                - git log -10 --date="format:%Y%m%d%H%M%S" --pretty="evok (%ad) unstable; urgency=medium%n%n  * %s%n%n -- %an <%ae>  %aD %n" > debian/changelog 
                - dpkg-buildpackage -us -uc
                - mkdir build
                # the packages generated by the dpkg-buildpackage are save in the upper directory
                # we need to move them to the working copy of the repository to be able to pass them to Gitlab as artifacts
                - mv ../evok_`git log -1  --date="format:%Y%m%d%H%M%S" --pretty="%ad"`* build/
        artifacts:
                paths:
                        - build/*
                        - debian/changelog

# build upon each pushed tag to the master branch
# the version is taken from the tag name
build_from_tagged_master_on_rpi:
        only:
                - tags
        except:
                - /^(!master)$/
        tags:
                - armhf
        script:
                - dpkg-buildpackage -us -uc
                - mkdir build
                - mv ../evok_`git log -1  --date="format:%Y%m%d%H%M%S" --pretty="%ad"`* build/
        artifacts:
                paths:
                        - build/*
                        - debian/changelog

build_from_tagged_master_on_nanopi:
        only:
                - tags
        except:
                - /^(!master)$/
        tags:
                - arm64
        script:
                - dpkg-buildpackage -us -uc
                - mkdir build
                - mv ../evok_`git log -1  --date="format:%Y%m%d%H%M%S" --pretty="%ad"`* build/
        artifacts:
                paths:
                        - build/*
                        - debian/changelog
