version: '3.5'
services:

  evok:
    build:
      context: .
      dockerfile: Dockerfile
    image: evok-test:devel
    restart: "no"
    command: ["python", "evok.py"]
#    env_file: &envfile
#      - .env
    volumes:
      - ./docker.evok.iris:/etc/evok.conf
      - ./var/evok-alias.yaml:/var/evok/evok-alias.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    extra_hosts:
#     - "flexibee.faster.cz:10.64.11.89"
#      - "flexi-tools:10.64.11.87"
#    depends_on:
#      - broker
#      - memcached

  nginx:
    image: nginx
    restart: "no"
    ports:
      - "8080:80"
#      - "443:443"
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www
    depends_on:
      - evok
