site_name: Evok documentation
site_url: https://evok.readthedocs.io/
site_author: Unipi technology
site_description: API of Unipi controllers
copyright: Copyright &copy; 2014 - 2024 Unipi technology
repo_url: https://github.com/UniPiTechnology/evok
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - content.action.edit
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - toc.follow

plugins:
  - search
  - privacy

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UniPiTechnology

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration:
    - General: configs/evok_configuration.md
    - Aliases: configs/aliases.md
    - HW definitions: configs/hw_definitions.md
  - Available APIs: apis.md
  - API examples:
      - Bulk: apis/bulk.md
      - JSON: apis/json.md
      - REST: apis/rest.md
      - RPC: apis/rpc.md
      - Webhook: apis/webhook.md
      - WebSocket: apis/websocket.md
  - Debugging: debugging.md
