site_name: Evok documentation
site_description: Unipi controllers API
repo_url: https://github.com/UniPiTechnology/evok
theme:
  name: material
  features:
    - content.action.edit
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - toc.follow

plugins:
  - search

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Installation: installation.md
  - Available APIs: apis.md
  - Debugging: debugging.md
  - Configuration:
    - General: configs/evok_configuration.md
    - Aliases: configs/aliases.md
    - HW definitions: configs/hw_definitions.md
  - API details:
      - Bulk: apis/bulk.md
      - JSON: apis/json.md
      - REST: apis/rest.md
      - RPC: apis/rpc.md
      - Webhook: apis/webhook.md
      - WebSocket: apis/websocket.md
