[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "evok"
version = "2.5.8"
authors = [
  { name="Martin Triska", email="triska@unipi.technology" },
  { name="Miroslav Ondra", email="bokula@unipi.technology" },
  { name="Patrik Kratochvil", email="kratochvil@unipi.technology" },
]
description = "Web service bridge for Unipi PLCs"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    'tmodbus[async-serial] == 0.6.2',
    'pymodbus >= 3.8.1, < 4',  # only ModbusBaseClient.convert_*_registers() with word_order
    'tornado == 6.3.3',
    'tornado-jsonrpc2 == 0.5',
    'jsonschema == 2.6.0',
    'pyyaml == 6.0.1',
    'anyio >= 3',
    'asyncowfs@git+https://github.com/UniPiTechnology/asyncowfs'
#    'asyncowfs@file:///home/unipi/packages/evok-internal/asyncowfs'
]

[tool.setuptools]
packages = ["evok"]
package-dir = {"" = "src"}

[project.scripts]
evok = "evok.evok:main"

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
