#!/bin/sh -e

#install/deinstall Unipi eprom
#  prog 24c01 0x57
#  prog -r 0x57

chip=$1
i2c=$2
test -z "$i2c" && exit 1
i2cdir=`printf "1-%04x" $i2c`

if [ "-r" = "$chip" ]; then  
  # Remove i2c device
  if [ -d /sys/class/i2c-dev/i2c-1/device/$i2cdir ]; then
      echo $i2c > /sys/class/i2c-dev/i2c-1/device/delete_device
  fi
  exit 0
fi

if [ -d /sys/class/i2c-dev/i2c-1/device/$i2cdir ]; then
    :  # already exists
else
   # create device
   echo "$chip $i2c" > /sys/class/i2c-dev/i2c-1/device/new_device
fi

if [ -d /sys/class/i2c-dev/i2c-1/device/$i2cdir ]; then
    if cat /sys/class/i2c-dev/i2c-1/device/$i2cdir/eeprom >/dev/null 2>&1; then
        exit 0
    fi
    echo $i2c > /sys/class/i2c-dev/i2c-1/device/delete_device
fi
exit 0
