name: Feature Request
description: Propose a new feature for the program
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature request, please try to provide as much information as possible.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
      placeholder: I want feature X to do Y.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Explain the use case of the feature. How will it benefit users?
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered, if any.
  - type: input
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request that can help us understand the request better.