version: '3.5'
services:
  evok:
    build:
      context: .
      dockerfile: Dockerfile
    image: evok
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./evok-alias.yaml
        target: /var/evok/evok-alias.yaml
      - type: bind
        source: ./evok-config.yaml
        target: /etc/evok/config.yaml
    ports:
      - "502:502"
    extra_hosts:
      - "host.docker.internal:host-gateway"
