#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from math import sqrt

from .client import Client


class PwmFrequency:
    """ PWM frequency shared by a group of digital outputs

        update() reads the frequency registers from the cache, set() writes
        a new frequency. The duty cycle of each output is kept in its own
        register, duty() and duty_raw() convert it between percent and
        the register value for the current frequency.
    """

    def __init__(self, client: Client):
        self.client = client
        self.freq = None

    def update(self) -> bool:
        """ Read the frequency from the cache, return True if it has changed """
        old_freq = self.freq
        self.freq = self._read()
        return old_freq != self.freq

    def _read(self) -> float:
        raise NotImplementedError

    async def set(self, freq: float):
        raise NotImplementedError

    def duty(self, raw: int) -> float:
        """ Return the duty cycle in percent from the register value """
        raise NotImplementedError

    def duty_raw(self, duty: float) -> int:
        """ Return the register value of the duty cycle in percent """
        raise NotImplementedError

    async def _write(self, values: dict):
        """ Write the registers, update the cache after all writes,
            so update() never sees a partial setting
        """
        for reg, value in values.items():
            await self.client.mb_client.write_single_register(reg, value)
        for reg, value in values.items():
            self.client.cache.set_register(reg, [value])


class HardPwmFrequency(PwmFrequency):
    """ PWM generated by a HW timer, freq = 48 MHz / (cycle * prescale)

        The registers keep cycle - 1 and prescale - 1, the duty register
        counts in timer cycles.
    """

    BASE_FREQ = 48000000

    def __init__(self, client: Client, regcycle: int, regprescale: int):
        super().__init__(client)
        self.regcycle = regcycle
        self.regprescale = regprescale
        self.cycle = None
        self.prescale = None

    def _read(self) -> float:
        self.cycle = self.client.read_u16(self.regcycle) + 1
        self.prescale = self.client.read_u16(self.regprescale) + 1
        return self.BASE_FREQ / (self.cycle * self.prescale)

    @classmethod
    def divide(cls, freq: float) -> tuple[int, int]:
        """ Return (cycle, prescale) for the frequency, a round cycle is preferred for a precise duty """
        delay = cls.BASE_FREQ / freq
        cycle = next((cycle for cycle in (50000, 10000, 5000, 1000)
                      if int(delay) % cycle == 0 and delay / cycle < 65535), None)
        if cycle is not None:
            prescale = round(delay / cycle)
        else:
            cycle = prescale = round(sqrt(delay))
        if not 1 <= prescale <= 65536:
            raise ValueError("Frequency out of range!")
        return cycle, prescale

    async def set(self, freq: float):
        cycle, prescale = self.divide(freq)
        await self._write({self.regcycle: cycle - 1, self.regprescale: prescale - 1})
        self.cycle, self.prescale = cycle, prescale
        self.freq = self.BASE_FREQ / (cycle * prescale)

    def duty(self, raw: int) -> float:
        return round(raw / self.cycle * 100, 1)

    def duty_raw(self, duty: float) -> int:
        return round(self.cycle * duty / 100)


class SoftPwmFrequency(PwmFrequency):
    """ PWM generated by the firmware

        The frequency is selected by a preset, or with the CUSTOM preset
        computed as 1000 Hz / (1 + prescaler). The duty register is in percent.
    """

    BASE_FREQ = 1000
    PRESETS = {0: 1000, 1: 100}
    CUSTOM = 2

    def __init__(self, client: Client, regpreset: int, regprescale: int):
        super().__init__(client)
        self.regpreset = regpreset
        self.regprescale = regprescale

    def _read(self) -> float:
        preset = self.client.read_u16(self.regpreset)
        if preset in self.PRESETS:
            return self.PRESETS[preset]
        return round(self.BASE_FREQ / (1 + self.client.read_u16(self.regprescale)), 1)

    async def set(self, freq: float):
        preset = next((preset for preset, preset_freq in self.PRESETS.items() if preset_freq == freq), None)
        if preset is not None:
            await self._write({self.regpreset: preset})
            self.freq = self.PRESETS[preset]
            return
        prescale = round(self.BASE_FREQ / freq - 1)
        if not 0 <= prescale <= 65535:
            raise ValueError("Frequency out of range!")
        await self._write({self.regpreset: self.CUSTOM, self.regprescale: prescale})
        self.freq = round(self.BASE_FREQ / (1 + prescale), 1)

    def duty(self, raw: int) -> float:
        return raw

    def duty_raw(self, duty: float) -> int:
        return round(duty)
