#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from math import sqrt

from .client import Client, Accessor, AccessorU16


class PwmFrequency:
    """ PWM frequency shared by a group of digital outputs

        update() reads the frequency registers from the cache, set() writes
        a new frequency. The duty cycle of each output is kept in its own
        register, duty() and duty_raw() convert it between percent and
        the register value for the current frequency.
    """

    def __init__(self, client: Client):
        self.client = client
        self.freq = None

    def update(self) -> bool:
        """ Read the frequency from the cache, return True if it has changed """
        old_freq = self.freq
        self.freq = self._read()
        return old_freq != self.freq

    def _read(self) -> float:
        raise NotImplementedError

    async def set(self, freq: float):
        raise NotImplementedError

    def duty(self, raw: int) -> float:
        """ Return the duty cycle in percent from the register value """
        raise NotImplementedError

    def duty_raw(self, duty: float) -> int:
        """ Return the register value of the duty cycle in percent """
        raise NotImplementedError

    async def _write(self, values: dict[Accessor, int]):
        """ Write the raw register values, update the cache after all writes,
            so update() never sees a partial setting (Accessor.write would
            update the cache after each register)
        """
        for accessor, value in values.items():
            await self.client.mb_client.write_single_register(accessor.index, value)
        for accessor, value in values.items():
            self.client.cache.set_register(accessor.index, [value])


class HardPwmFrequency(PwmFrequency):
    """ PWM generated by a HW timer, freq = 48 MHz / (cycle * prescale)

        The registers keep cycle - 1 and prescale - 1, the duty register
        counts in timer cycles.
    """

    BASE_FREQ = 48000000

    def __init__(self, client: Client, regcycle: int, regprescale: int):
        super().__init__(client)
        self.accessor_cycle = AccessorU16(regcycle)
        self.accessor_prescale = AccessorU16(regprescale)
        self.cycle = None
        self.prescale = None

    def _read(self) -> float:
        self.cycle = self.accessor_cycle.read(self.client) + 1
        self.prescale = self.accessor_prescale.read(self.client) + 1
        return self.BASE_FREQ / (self.cycle * self.prescale)

    @classmethod
    def divide(cls, freq: float) -> tuple[int, int]:
        """ Return (cycle, prescale) for the frequency, a round cycle is preferred for a precise duty """
        delay = cls.BASE_FREQ / freq
        cycle = next((cycle for cycle in (50000, 10000, 5000, 1000)
                      if int(delay) % cycle == 0 and delay / cycle < 65535), None)
        if cycle is not None:
            prescale = round(delay / cycle)
        else:
            cycle = prescale = round(sqrt(delay))
        if not 1 <= prescale <= 65536:
            raise ValueError("Frequency out of range!")
        return cycle, prescale

    async def set(self, freq: float):
        cycle, prescale = self.divide(freq)
        await self._write({self.accessor_cycle: cycle - 1, self.accessor_prescale: prescale - 1})
        self.cycle, self.prescale = cycle, prescale
        self.freq = self.BASE_FREQ / (cycle * prescale)

    def duty(self, raw: int) -> float:
        return round(raw / self.cycle * 100, 1)

    def duty_raw(self, duty: float) -> int:
        return round(self.cycle * duty / 100)


class SoftPwmFrequency(PwmFrequency):
    """ PWM generated by the firmware

        The frequency is selected by a preset, or with the CUSTOM preset
        computed as 1000 Hz / (1 + prescaler). The duty register is in percent.
    """

    BASE_FREQ = 1000
    PRESETS = {0: 1000, 1: 100}
    CUSTOM = 2

    def __init__(self, client: Client, regpreset: int, regprescale: int):
        super().__init__(client)
        self.accessor_preset = AccessorU16(regpreset)
        self.accessor_prescale = AccessorU16(regprescale)

    def _read(self) -> float:
        preset = self.accessor_preset.read(self.client)
        if preset in self.PRESETS:
            return self.PRESETS[preset]
        return round(self.BASE_FREQ / (1 + self.accessor_prescale.read(self.client)), 1)

    async def set(self, freq: float):
        preset = next((preset for preset, preset_freq in self.PRESETS.items() if preset_freq == freq), None)
        if preset is not None:
            await self._write({self.accessor_preset: preset})
            self.freq = self.PRESETS[preset]
            return
        prescale = round(self.BASE_FREQ / freq - 1)
        if not 0 <= prescale <= 65535:
            raise ValueError("Frequency out of range!")
        await self._write({self.accessor_preset: self.CUSTOM, self.accessor_prescale: prescale})
        self.freq = round(self.BASE_FREQ / (1 + prescale), 1)

    def duty(self, raw: int) -> float:
        return raw

    def duty_raw(self, duty: float) -> int:
        return round(duty)
