#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from math import ceil

from .client import Client, Accessor, AccessorU16


def round_freq(freq: float) -> float:
    """ The frequency for the API, by 0.1 Hz, below 1 Hz finer, it would be 0 """
    return round(freq, 1 if freq >= 1 else 4)


class PwmFrequency:
    """ PWM frequency shared by a group of digital outputs

        update() reads the frequency registers from the cache, set() writes
        a new frequency. The duty cycle of each output is kept in its own
        register, duty() and duty_raw() convert it between percent and
        the register value for the current frequency.
    """

    def __init__(self, client: Client):
        self.client = client
        self.freq = None

    def update(self) -> bool:
        """ Read the frequency from the cache, return True if it has changed """
        old_freq = self.freq
        self.freq = self._read()
        return old_freq != self.freq

    def _read(self) -> float:
        raise NotImplementedError

    async def set(self, freq: float):
        raise NotImplementedError

    def duty(self, raw: int) -> float:
        """ Return the duty cycle in percent from the register value """
        raise NotImplementedError

    def duty_raw(self, duty: float) -> int:
        """ Return the register value of the duty cycle in percent """
        raise NotImplementedError

    async def _write(self, values: dict[Accessor, int]):
        """ Write the raw register values, update the cache after all writes,
            so update() never sees a partial setting (Accessor.write would
            update the cache after each register)

            The adjacent registers are written by one request, the unit does not run
            with a partial setting between two requests.
        """
        registers = sorted((accessor.index, value) for accessor, value in values.items())
        runs = []
        for index, value in registers:
            if runs and runs[-1][0] + len(runs[-1][1]) == index:
                runs[-1][1].append(value)
            else:
                runs.append((index, [value]))
        for index, run in runs:
            if len(run) == 1:
                await self.client.mb_client.write_single_register(index, run[0])
            else:
                await self.client.mb_client.write_multiple_registers(index, run)
        for index, value in registers:
            self.client.cache.set_register(index, [value])


class HardPwmFrequency(PwmFrequency):
    """ PWM generated by a HW timer, freq = 48 MHz / (cycle * prescale)

        The registers keep cycle - 1 and prescale - 1, the duty register
        counts in timer cycles, the longest cycle has the finest duty.
    """

    BASE_FREQ = 48000000
    MAX_FREQ = 50000        # [Hz] a cycle of 960 timer cycles, the duty by 0.1 %
    MAX_REGISTER = 65536    # cycle and prescale, the registers keep them - 1

    def __init__(self, client: Client, regcycle: int, regprescale: int):
        super().__init__(client)
        self.accessor_cycle = AccessorU16(regcycle)
        self.accessor_prescale = AccessorU16(regprescale)
        self.cycle = None
        self.prescale = None

    def _read(self) -> float:
        self.cycle = self.accessor_cycle.read(self.client) + 1
        self.prescale = self.accessor_prescale.read(self.client) + 1
        return self.frequency(self.cycle, self.prescale)

    @classmethod
    def frequency(cls, cycle: int, prescale: int) -> float:
        return round_freq(cls.BASE_FREQ / (cycle * prescale))

    @classmethod
    def divide(cls, freq: float) -> tuple[int, int]:
        """ Return (cycle, prescale) for the frequency, the smallest prescale gives the longest cycle

            A cycle of the same length for all frequencies, e.g. 49 * 49 for 20 kHz,
            had a duty by 2 % and the frequency 19991.7 Hz.
        """
        min_freq = cls.BASE_FREQ / cls.MAX_REGISTER ** 2
        if not min_freq <= freq <= cls.MAX_FREQ:
            raise ValueError(f"Frequency {freq} Hz out of range <{min_freq:.3f}..{cls.MAX_FREQ}> Hz")
        delay = cls.BASE_FREQ / freq
        prescale = ceil(delay / cls.MAX_REGISTER)
        cycle = min(round(delay / prescale), cls.MAX_REGISTER)
        return cycle, prescale

    async def set(self, freq: float):
        cycle, prescale = self.divide(freq)
        await self._write({self.accessor_cycle: cycle - 1, self.accessor_prescale: prescale - 1})
        self.cycle, self.prescale = cycle, prescale
        self.freq = self.frequency(cycle, prescale)

    def duty(self, raw: int) -> float:
        return round(raw / self.cycle * 100, 1)

    def duty_raw(self, duty: float) -> int:
        return round(self.cycle * duty / 100)


class SoftPwmFrequency(PwmFrequency):
    """ PWM generated by the firmware

        The frequency is selected by a preset, or with the CUSTOM preset
        computed as 1000 Hz / (1 + prescaler). The duty register is in percent.
    """

    BASE_FREQ = 1000
    PRESETS = {0: 1000, 1: 100}
    CUSTOM = 2

    def __init__(self, client: Client, regpreset: int, regprescale: int):
        super().__init__(client)
        self.accessor_preset = AccessorU16(regpreset)
        self.accessor_prescale = AccessorU16(regprescale)

    def _read(self) -> float:
        preset = self.accessor_preset.read(self.client)
        if preset in self.PRESETS:
            return self.PRESETS[preset]
        return round_freq(self.BASE_FREQ / (1 + self.accessor_prescale.read(self.client)))

    async def set(self, freq: float):
        preset = next((preset for preset, preset_freq in self.PRESETS.items() if preset_freq == freq), None)
        if preset is not None:
            await self._write({self.accessor_preset: preset})
            self.freq = self.PRESETS[preset]
            return
        prescale = round(self.BASE_FREQ / freq - 1)
        if not 0 <= prescale <= 65535:
            raise ValueError("Frequency out of range!")
        await self._write({self.accessor_preset: self.CUSTOM, self.accessor_prescale: prescale})
        self.freq = round_freq(self.BASE_FREQ / (1 + prescale))

    def duty(self, raw: int) -> float:
        return raw

    def duty_raw(self, duty: float) -> int:
        return round(duty)
