"""
Structure for device data. Generated by the "real" server,
but when we're testing we don't have that.
"""

# Feel free to add data from other device types as required.

structs = {
    "10": {
        "address": "a,000000,000001,ro,000016,f,",
        "alias": "l,000000,000001,rw,000256,f,",
        "crc8": "a,000000,000001,ro,000002,f,",
        "family": "a,000000,000001,ro,000002,f,",
        "id": "a,000000,000001,ro,000012,f,",
        "latesttemp": "t,000000,000001,ro,000012,v,",
        "locator": "a,000000,000001,ro,000016,f,",
        "power": "y,000000,000001,ro,000001,v,",
        "temperature": "t,000000,000001,ro,000012,v,",
        "temphigh": "t,000000,000001,rw,000012,s,",
        "templow": "t,000000,000001,rw,000012,s,",
        "type": "a,000000,000001,ro,000032,f,",
        "foo": {
            "bar": "i,000000,000001,rw,000012,s,",
            "baz": {"quux": "f,000000,000001,rw,000012,s,"},
            "plugh.A": "i,00000,000001,rw,000012,s,",
            "plover.0": "i,00000,000001,rw,000012,s,",
        },
    },
    "1F": {},
    "20": {},
    "28": {},
}
