#!/bin/bash

FILENAME='version.txt'

exec 1>&2
REPONAME=`basename \`git rev-parse --show-toplevel\``
BRANCH=`git rev-parse --abbrev-ref HEAD`
SHORTHASH=`git log --pretty=format:'%h' -n 1`
REVCOUNT=`git log --oneline | wc -l`
LATESTTAG=`git describe --tags --abbrev=0`

VERSION="$REPONAME Branch:[$BRANCH] Release:$LATESTTAG PrecedingRevision:$REVCOUNT($SHORTHASH)"
echo $VERSION > $FILENAME
git update-index --assume-unchanged $FILENAME